# Theme
# solarized dark
# fleet_dark
# Monokai
# NightFox
# gruvbox_draken
# base16_default_dark
# jellybeans
# nord-night
# rasmus
theme = "gruvbox_dark_hard"

# General Helix's configuration
[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-completion = true
auto-format = true
true-color = true

# Cursor type
[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

# Helix's statusline
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-base-name", "diagnostics"]
right = ["position", "file-encoding", "separator", "workspace-diagnostics", "version-control"]
separator = " "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# File explorer configuration
[editor.file-picker]
hidden = false
parents = false

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = false
character = "⸽" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# LSP Server configuration
[editor.lsp]
display-messages = true
auto-signature-help	= true
display-signature-help-docs	= true

# Auto-pairs
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
"'" = "'"

# Remapping some Keymaps
[keys.normal]
C-s = ":w" # Maps the Ctrl-s to the typable command :w which is an alias for :write (save file)
C-h = "move_prev_word_end"
C-l = "move_next_word_start"
C-a = "select_all"
y = "yank_joined_to_clipboard"
p = "paste_clipboard_after"

[keys.insert]
k = { j = "normal_mode" } # Maps `kj` to exit insert mode
C-left = "move_prev_word_start"
C-right = "move_next_word_end"
