"string" = "green"
"type" = { fg = "yellow", modifiers = ["bold"] }
"type.builtin" = { fg = "yellow", modifiers = ["bold"] }
"comment" = "brown"
"keyword" = { fg = "yellow", modifiers = ["bold"] }
"keyword.directive" = "quartz"
"function" = { fg = "#95a99f" }
"function.builtin" = { fg = "yellow" }
"ui.cursor" = { fg = "background-1", bg = "yellow", modifiers = ["rapid_blink"] }
"ui.popup" = { bg = "background" }

"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

"warning" = "yellow"
"error" = "red"
"info" = "quartz"
"hint" = "wisteria"

"ui.background" = { bg = "background-1" }
"ui.linenr" = "background_2"
"ui.linenr.selected" = "yellow"
"ui.selection" = { bg = "#3a3d41" }

"ui.statusline" = { fg = "foreground", bg = "background_1" } # Status line.
"ui.statusline.inactive" = { fg = "foreground", bg = "background_2" } # Status line in unfocused windows.
"ui.statusline.normal" = { bg = "yellow", fg = "background_2", modifiers = ["bold"] } # Statusline mode during normal mode (only if editor.color-modes is enabled)
"ui.statusline.insert" = { bg = "niagara", fg = "background_2", modifiers = ["bold"] } # Statusline mode during insert mode (only if editor.color-modes is enabled)
"ui.statusline.select" = { bg = "red", fg = "background_2", modifiers = ["bold"] } # Statusline mode during select mode (only if editor.color-modes is enabled)



[palette]
# gruber darker palette colors
# colors with _x are lighter. -x are darker.
foreground = "#e4e4ef"
foreground_1 = "#f4f4ff"
foreground_2 = "#f5f5f5"
white = "#ffffff"
black = "#000000"
background = "#101010"
background-1 = "#181818"
background_1 = "#282828"
background_2 = "#453d41"
background_3 = "#484848"
background_4 = "#52494e"
red-1 = "#c73c3f"
red = "#f43841"
red_1 = "#ff4f58"
green = "#73c936"
yellow = "#ffdd33"
brown = "#cc8c3c"
quartz = "#95a99f"
niagara-2 = "#303540"
niagara-1 = "#565f73"
niagara = "#96a6c8"
wisteria = "#9e95c7"
